### ISSUE TITLE
KiCAD v5.1.7 shows lot of airwires on board

### ISSUE THREAD

**Issue by warlock31415** [dc-power-supply/dc-power-supply#1]
![Screenshot from 2020-10-03 18-53-27](https://user-images.githubusercontent.com/26103385/95004549-c94fe380-05a9-11eb-9acd-9ebbb657e416.png)
I just clones the repo. Noticed that there were a lot of air wires on the board. Was this design ever finished? Can i finish the board and submit a pull request? 

Thanks,
Pratik

**Comment by lundmar** [comment]
Hi Pratik,
Sure - feel free to upgrade it to KiCad 5.1.7 and finish up the design :+1: 
I never really got around to finish up the missing microcontroller part of the PCB design. I have too many projects going on IRL :)
/Martin

**Comment by warlock31415** [comment]
Okay, but i'm gonna need a little help. never worked with ethernet before. Will create more issues on here for more specific questions.

/Pratik
